language: objective-c

branches:
 only:
 - master

xcode_project: Identifiable.xcodeproj
xcode_scheme: IdentifiableTests
osx_image: xcode8.1
xcode_sdk: iphonesimulator10.1

script:
- xcodebuild clean build test -project Identifiable.xcodeproj -scheme Identifiable
